# Generated by Django 4.1.4 on 2023-01-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=20, unique=True),
        ),
    ]
